### ISSUE TITLE
README examples out of date

### ISSUE THREAD

**Issue by DSpeichert** [dropbox/dropbox-sdk-go-unofficial#4]
All the examples in README have wrong import paths, function signatures, etc.

**Comment by diwakergupta** [comment]
It certainly is, especially with the breaking changes I pushed last night! Thanks for flagging @DSpeichert , I'll fix this in the next few hours.

**Comment by diwakergupta** [comment]
This should be fixed now. I will be adding more information to the README this week.

**Comment by DSpeichert** [comment]
Great, thanks!

**Comment by DSpeichert** [comment]
The following example is still wrong:
```
  arg := users.NewGetAccountArg()
  if resp, err := dbx.GetAccount(arg); err != nil {
    return err
  }
  fmt.Printf("Name: %v", resp.Name)
```
`not enough arguments in call to users.NewGetAccountArg`

**Comment by diwakergupta** [comment]
They're just meant to be illustrative, the exact API is easily checked in godocs. Regardless, will fix. BTW, I welcome pull requests :)

**Comment by DSpeichert** [comment]
I get it and found my way around (actually was looking for GetCurrentUsers). I'm working on an app in Go that will use webhooks and check deltas and pull modified files so new issues and/or PRs are likely coming soon :)
